# See the documentation for alacritty.toml at
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

# You can find these themes and many more at
# https://github.com/alacritty/alacritty-theme
import = [
    # "~/.config/alacritty/themes/themes/breeze.toml"
    "~/.config/alacritty/themes/themes/aura.toml"
    # "~/.config/alacritty/themes/themes/github_dark.toml"
    # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR="1.0"

[window]
resize_increments = false
opacity = 0.7
startup_mode = "Windowed"
title = "Alacritty - zsh"
dimensions = { columns = 126, lines = 26}
padding = { y = 2 }


[scrolling]
history = 50000

[font]
size = 10.25
normal.family = "MesloLGS Nerd Font"
# normal.family = "Fira Code"

[keyboard]
bindings = [
    # {key = "V", mods = "Control|Shift", action = "Paste"},
    # {key = "C",mods = "Control|Shift",action = "Copy"},

    {key = "W",mods = "Control|Shift",action = "Quit"},

    {key = "T",mods = "Control|Shift",action = "SpawnNewInstance"},
    {key = "N",mods = "Control|Shift",action = "CreateNewWindow"},

    {key = "PageUp",mods = "Shift",action = "ScrollPageUp"},
    {key = "PageDown",mods = "Shift",action = "ScrollPageDown"},
    
    {key = "Home",mods = "Shift",action = "ScrollToTop"},
    {key = "End",mods = "Shift",action = "ScrollToBottom"},

]
